# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "À propos"
url = "a-propos/"
weight = 2

[[main]]
weight = 3
name = "Produits"
hasChildren = true

  [[main]]
  parent = "Produits"
  name = "Axyl Drive"
  url = "blog/post-1/"
  weight = 1

[[main]]
weight = 4
name = "Services"
hasChildren = true

  [[main]]
  parent = "Services"
  name = "Axyl School"
  url = "blog/post-2/"
  weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 5

# footer menu
[[footer]]
name = "À propos"
url = "a-propos/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Produits"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Termes et Conditions"
url = "terms-and-conditions/"
weight = 4